jobs:
  build:
    permissions:
      contents: "write"
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }} | ${{ matrix.job.variant || 'default' }})
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: "actions/checkout@v4"
      - run: |
          echo "PROJECT_VERSION=$(sed -n 's/^      version: "\(.*\)"/\1/p' mix.exs)" >> $GITHUB_ENV
        shell: "bash"
      - uses: "dtolnay/rust-toolchain@1.82.0"
        with:
          target: ${{ matrix.job.target }}
      - id: "build-crate"
        uses: "philss/rustler-precompiled-action@v1.1.4"
        with:
          nif-version: ${{ matrix.nif }}
          project-name: "deno_rider"
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          use-cross: ${{ matrix.job.use-cross }}
          variant: ${{ matrix.job.variant }}
      - uses: "actions/upload-artifact@v4"
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: "softprops/action-gh-release@v2"
        with:
          files: ${{ steps.build-crate.outputs.file-path }}
    strategy:
      fail-fast: false
      matrix:
        nif: ["2.15"]
        job:
          - os: "ubuntu-22.04"
            variant: "use_old_glibc"
            target: "x86_64-unknown-linux-gnu"
          - os: "macos-13"
            target: "aarch64-apple-darwin"
          - os: "ubuntu-24.04"
            target: "aarch64-unknown-linux-gnu"
            use-cross: true
          - os: "macos-13"
            target: "x86_64-apple-darwin"
          - os: "windows-2022"
            target: "x86_64-pc-windows-msvc"
          - os: "ubuntu-24.04"
            target: "x86_64-unknown-linux-gnu"
on:
  push:
    tags: ["*"]
  workflow_dispatch:
